name: flutterfire_gen
description: flutterfire_gen is a package for automatic code generation for Cloud Firestore. It supports efficient CRUD operations with type-safe interfaces and methods.
version: 0.4.3
homepage: https://github.com/kosukesaigusa/flutterfire_gen

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  analyzer: ">=5.13.0 <7.0.0"
  build: ^2.4.1
  cloud_firestore: ^4.14.0
  flutter:
    sdk: flutter
  flutterfire_gen_annotation: ^0.4.1
  flutterfire_gen_utils: ^0.4.1
  json_annotation: ^4.8.1
  meta: ^1.9.1
  path: ^1.8.3
  source_gen: ^1.5.0

dev_dependencies:
  build_runner: ^2.4.7
  mockito: ^5.4.4
  test: ^1.21.0

# https://dart.dev/tools/pub/pubspec#platforms
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:
