name: riverpod_generator_todo_example
description: A new Flutter project.
publish_to: 'none'
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  cloud_firestore: ^6.1.1
  firebase_core: ^4.3.0
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  flutterfire_gen_annotation:
    path: ../../packages/flutterfire_gen_annotation
  flutterfire_gen_utils:
    path: ../../packages/flutterfire_gen_utils
  riverpod_annotation: ^2.6.1

dev_dependencies:
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  flutter_test:
    sdk: flutter
  flutterfire_gen:
    path: ../../packages/flutterfire_gen
  riverpod_generator: ^2.6.3
  riverpod_lint: ^2.6.3

flutter:
  uses-material-design: true
